export class RandomContentManager {
    constructor(category) {
        this.category = category;
        this.randomExcerpts = [];
        this.randomTags = [];
        this.randomTitles = [];

        this.dataByCategory = {
            1: {
                titles: [
                    "Preserving Wildlife: Our Mission",
                    "Join Us in Protecting Nature",
                    "Wildlife Conservation Efforts",
                    "Saving Endangered Species",
                    "Empowering Wildlife Guardians",
                    "Supporting Wildlife Rehabilitation",
                    "Safeguarding Animal Habitats",
                    "Championing Wildlife Education",
                    "A Future Where Wildlife Thrives",
                    "Together for Wildlife Preservation",
                    "Creating a Safe Haven for Animals",
                    "Sustainable Wildlife Solutions",
                    "Unite for Wildlife Conservation",
                    "Caring for Our Animal Friends",
                    "Advocating for Wildlife Rights",
                    "Building a Better World for Wildlife",
                    "Education for Wildlife Awareness",
                    "Our Commitment to Wildlife Protection",
                    "Protecting the Wild Ones",
                    "Rescue, Rehabilitate, Release: Our Pledge",
                    "Wildlife in Crisis: Our Response",
                    "Conservation Heroes in Action",
                    "Hope for Endangered Wildlife",
                    "Connecting People with Nature",
                    "Join the Fight for Wildlife Survival",
                    "A Home for Every Species",
                    "Empowering Communities for Wildlife",
                    "Preserving Biodiversity Together",
                    "Wildlife: Our Shared Responsibility",
                    "For a Future Where All Species Thrive",
                    "Wildlife Preservation: Our Legacy",
                    "From Crisis to Conservation: Our Journey",
                    "Innovations for Wildlife Protection",
                    "Empathy, Education, and Wildlife Care",
                    "A Voice for the Voiceless Creatures",
                    "Sustaining Life on Earth: Our Calling",
                    "Protecting the Web of Life",
                    "Inspiring Love and Respect for Wildlife",
                    "Join Us in the Wildlife Crusade",
                    "Nature's Guardians: Our Role"
                ],
                excerpts: [
                    "Our mission is to preserve and protect wildlife for future generations.",
                    "Join us in the noble cause of protecting and conserving nature's treasures.",
                    "Discover our dedicated efforts in wildlife conservation and habitat preservation.",
                    "We're committed to saving endangered species from the brink of extinction.",
                    "Empower wildlife guardians to defend and nurture our planet's precious creatures.",
                    "Support wildlife rehabilitation programs to give injured animals a second chance at life.",
                    "Safeguard animal habitats to ensure they thrive in their natural environments.",
                    "Champion wildlife education to foster a deeper connection between people and nature.",
                    "We envision a future where wildlife flourishes in harmony with our world.",
                    "Join us in our mission to come together for the preservation of wildlife.",
                    "Help us create safe havens for animals to live, thrive, and roam freely.",
                    "Discover sustainable solutions that protect and sustain our planet's wildlife.",
                    "Unite with us in the fight for the conservation of precious wildlife species.",
                    "Our commitment extends to caring for and protecting our animal friends.",
                    "Advocate for the rights and welfare of wildlife worldwide.",
                    "We're building a better world where wildlife can thrive and coexist with humans.",
                    "Education is key to raising awareness about the importance of wildlife in our lives.",
                    "Explore our unwavering commitment to protecting and preserving wildlife.",
                    "Join us in our mission to protect the wild ones who share our planet.",
                    "Our pledge is to rescue, rehabilitate, and release animals in need.",
                    "Learn about our response to wildlife in crisis and how you can make a difference.",
                    "Discover the conservation heroes who are actively working to protect our planet's wildlife.",
                    "We offer hope for endangered wildlife by supporting conservation initiatives.",
                    "Our goal is to connect people of all ages with the wonders of the natural world.",
                    "Join the fight to ensure the survival of wildlife species for generations to come.",
                    "We believe every species deserves a safe and nurturing home in the wild.",
                    "Empower communities to become champions for wildlife preservation.",
                    "Together, we can preserve biodiversity and protect our planet's wildlife.",
                    "Wildlife conservation is a shared responsibility we all must embrace.",
                    "Join us in our mission for a future where all species thrive on Earth.",
                    "Our legacy is built upon a commitment to preserving and protecting wildlife.",
                    "Explore our journey from crisis to conservation as we strive to save species.",
                    "Discover innovative solutions that safeguard wildlife and their natural habitats.",
                    "We promote empathy, education, and compassionate care for all creatures.",
                    "Be a voice for the voiceless creatures who depend on our stewardship.",
                    "Our calling is to sustain life on Earth by protecting and preserving wildlife.",
                    "Protecting the web of life is essential for the survival of our planet.",
                    "We inspire love and respect for wildlife in the hearts of people worldwide.",
                    "Join us in the wildlife crusade to protect and conserve our natural world.",
                    "Discover our role as nature's guardians and advocates for wildlife preservation."
                ],
                tags: [
                    "Wildlife Preservation",
                    "Conservation",
                    "Habitat Protection",
                    "Endangered Species",
                    "Animal Rehabilitation",
                    "Habitat Safeguard",
                    "Wildlife Education",
                    "Future for Wildlife",
                    "Community Empowerment",
                    "Biodiversity",
                    "Shared Responsibility",
                    "Safe Havens",
                    "Sustainable Solutions",
                    "Unification for Wildlife",
                    "Animal Care",
                    "Advocacy",
                    "Better World",
                    "Education for Awareness",
                    "Commitment to Protection",
                    "Protecting the Wild",
                    "Rescue and Release",
                    "Response to Crisis",
                    "Conservation Heroes",
                    "Hope for Wildlife",
                    "Nature Connection",
                    "Fight for Survival",
                    "Safe Homes",
                    "Empowering Communities",
                    "Preserving Biodiversity",
                    "Global Responsibility",
                    "Thriving Species",
                    "Legacy of Preservation",
                    "From Crisis to Conservation",
                    "Innovations for Protection",
                    "Empathy and Education",
                    "Voice for Wildlife",
                    "Sustaining Life",
                    "Web of Life",
                    "Love for Wildlife",
                    "Wildlife Crusade",
                    "Guardianship of Nature"
                ]
            },
            2: {
                titles: [
                    "Exploring Hidden Wonders Worldwide",
                    "Wildlife Safari Adventures in Africa",
                    "Unraveling the Climate Change Challenge",
                    "Deep Ocean Mysteries Revealed",
                    "Journey Through Millennia of History",
                    "Nature's Breathtaking Beauty Unveiled",
                    "Surviving the Wilderness: Tales of Resilience",
                    "Epic Landscapes Across the Globe",
                    "Earth's Ever-Shifting Landscape",
                    "Rare Wildlife Encounters in the Wilderness",
                    "Into the Heart of the Amazon Rainforest",
                    "Unveiling Underwater Enigmas",
                    "Human History Unearthed",
                    "Preserving Earth's Fragile Ecosystems",
                    "Unlocking Ancient Ruins' Secrets",
                    "Up Close with Earth's Wild Creatures",
                    "Chasing the Enigmatic Aurora Borealis",
                    "Tales of Daring Global Expeditions",
                    "Oceans: A World of Wonders",
                    "Rediscovering Ancient Civilizations' Grandeur",
                    "Marvels of Nature: Secrets Exposed",
                    "African Safaris: Wildlife Adventures Await",
                    "The Urgent Battle Against Climate Change",
                    "Deep-Sea Discoveries and Ocean Wonders",
                    "A Historical Odyssey Through Time",
                    "Nature's Beauty: Awe-Inspiring Spectacles",
                    "Survival Stories: Facing the Wilderness",
                    "Scenic Marvels Across Continents",
                    "Our Changing Planet: Transformations Unveiled",
                    "Rare Wildlife: Extraordinary Encounters",
                    "Amazon Expedition: Journey to the Unknown",
                    "Beneath the Waves: Ocean Treasures",
                    "Archaeological Marvels: Ancient Secrets Revealed",
                    "Guardians of Ecosystems: Conservation Tales",
                    "Ancient Mysteries Unveiled: Ruins Explored",
                    "Wild Kingdom: Close Encounters with Wildlife",
                    "Chasing Northern Lights: Aurora Adventures",
                    "Explorer Chronicles: Adventures Beyond Boundaries",
                    "Marine Wonders: Dive into Ocean Diversity",
                    "Rediscovering Civilizations: Ancient Legacy Revived",
                    "The Beauty of the Natural World",
                    "Wildlife Safaris: African Adventures Await",
                    "Climate Crisis: The Urgent Call to Action",
                    "Beneath the Surface: Oceanic Marvels Revealed"
                ],
                excerpts: [
                    "Discover breathtaking landscapes and hidden wonders in this thrilling journey.",
                    "Embark on a wildlife safari like never before and witness the circle of life.",
                    "Gain deep insights into the pressing issue of climate change and its consequences.",
                    "Dive into the mysteries of the ocean depths and encounter fascinating creatures.",
                    "Take a captivating journey through time and explore the history of our world.",
                    "Immerse yourself in the spectacular beauty of nature's most stunning locations.",
                    "Learn the art of survival in the wild as we share stories of resilience and courage.",
                    "Unveil epic landscapes from around the globe, each with its own unique charm.",
                    "Witness the ever-changing landscape of our planet and its stunning transformations.",
                    "Experience rare encounters with some of the world's most extraordinary animals.",
                    "Embark on an adventure into the heart of the Amazon jungle and uncover its secrets.",
                    "Dive into the depths of the ocean to unveil its hidden wonders and mysteries.",
                    "Uncover the secrets of human history through archaeological discoveries.",
                    "Explore the fragile ecosystems of our Earth and the efforts to protect them.",
                    "Journey to ancient ruins and unlock the mysteries of civilizations long past.",
                    "Get up close and personal with wild creatures in their natural habitats.",
                    "Chase the elusive Aurora Borealis and witness the magic of the northern lights.",
                    "Join daring expeditions to the most extreme and remote corners of the Earth.",
                    "Dive into the depths of our oceans and discover their fascinating biodiversity.",
                    "Rediscover the wonders of ancient civilizations and their enduring legacies."
                ],
                tags: [
                    "Nature",
                    "Wildlife",
                    "Climate",
                    "Ocean",
                    "History",
                    "Survival",
                    "Landscape",
                    "Change",
                    "Adventure",
                    "Science",
                    "Exploration",
                    "Discovery",
                    "Conservation",
                    "Journey",
                    "Biodiversity",
                    "Ancient World",
                    "Eco-Warriors",
                    "Extreme Expeditions",
                    "Marine Life",
                    "Culture"
                ]
            },
            3: {
                titles: [
                    "Innovations in Technology",
                    "Designing Future Solutions",
                    "Tech Trends: What's Next?",
                    "The Art of User Interface",
                    "Exploring Digital Design",
                    "Revolutionizing Tech Industry",
                    "Designing for User Experience",
                    "Coding: The Creative Craft",
                    "The Future of AI and Robotics",
                    "Sustainable Tech Solutions",
                    "Cybersecurity Challenges Ahead",
                    "Design Thinking in Action",
                    "The World of Virtual Reality",
                    "Advancements in Data Science",
                    "Tech Startups: Success Stories",
                    "Graphic Design Evolution",
                    "Gaming Technology Unleashed",
                    "Digital Marketing Strategies",
                    "IoT: Connecting Our World",
                    "Artificial Intelligence Insights",
                    "Designing for Accessibility",
                    "Space Exploration Technology",
                    "Future of Mobile Apps",
                    "Eco-Friendly Design Practices",
                    "The Blockchain Revolution",
                    "Smart Cities of Tomorrow",
                    "Web Development Trends",
                    "Augmented Reality Experiences",
                    "Data Privacy in the Digital Age",
                    "Emerging Tech in Healthcare",
                    "Product Design Innovations",
                    "Cryptocurrency & Finance",
                    "3D Printing: Shaping the Future",
                    "UX/UI Design Principles",
                    "AI in Healthcare: Transforming Lives",
                    "Digital Illustration Mastery",
                    "Cybersecurity in a Connected World",
                    "Designing Sustainable Cities",
                    "Tech Entrepreneurship Journey",
                    "The Future of Wearables",
                    "AR/VR Gaming Adventures",
                    "Cryptocurrency Revolution"
                ],
                excerpts: [
                    "Explore the latest innovations in technology that are changing our world.",
                    "Designing for the future means creating solutions that stand the test of time.",
                    "Stay ahead with insights into the ever-evolving tech trends and developments.",
                    "User interface design is an art form that blends functionality and aesthetics.",
                    "Dive into the world of digital design and discover its endless possibilities.",
                    "Witness the revolution taking place in the technology and design industries.",
                    "Design with the user in mind to create exceptional experiences and products.",
                    "Coding is more than a skill; it's a creative craft that shapes the digital world.",
                    "The future is AI and robotics, and we're on the cusp of incredible advancements.",
                    "Explore sustainable tech solutions that are making a positive impact.",
                    "As technology advances, so do the challenges in keeping our data safe.",
                    "Design thinking is a powerful approach to problem-solving and innovation.",
                    "Step into a world of virtual reality and experience the future firsthand.",
                    "Data science is unlocking new possibilities and insights across industries.",
                    "Discover the stories of successful tech startups and their journeys to the top.",
                    "Graphic design continues to evolve, shaping the visual language of our world.",
                    "Gaming technology is pushing boundaries and providing immersive experiences.",
                    "Digital marketing strategies are essential in today's competitive landscape.",
                    "The Internet of Things is connecting and transforming our world in unprecedented ways.",
                    "Artificial intelligence is reshaping industries and driving innovation.",
                    "Design for accessibility to ensure technology is inclusive and user-friendly.",
                    "Technology plays a crucial role in the exploration and understanding of space.",
                    "The future of mobile apps is bright, with exciting developments on the horizon.",
                    "Embrace eco-friendly design practices that reduce our impact on the environment.",
                    "Blockchain technology is changing the way we transact and secure data.",
                    "Smart cities are the urban centers of tomorrow, leveraging tech for efficiency.",
                    "Stay updated on the latest web development trends and best practices.",
                    "Augmented reality offers new dimensions of interactive and immersive experiences.",
                    "Data privacy is a paramount concern in the digital age; stay informed.",
                    "Emerging tech is revolutionizing healthcare, improving patient outcomes.",
                    "Product design innovations are shaping the products we use and love.",
                    "Explore the intersection of cryptocurrency and the financial industry.",
                    "3D printing is unlocking creative possibilities and transforming manufacturing.",
                    "Master UX/UI design principles to create user-centric digital experiences.",
                    "AI is making a profound impact on healthcare, enhancing diagnosis and treatment.",
                    "Digital illustration is an art form that combines creativity with technology.",
                    "Navigate the complex world of cybersecurity in an increasingly connected world.",
                    "Design cities for sustainability, where technology enhances quality of life.",
                    "Embark on an entrepreneurial journey in the ever-evolving tech industry.",
                    "Wearables are changing the way we interact with technology and monitor health.",
                    "Experience the adventures of AR/VR gaming and explore virtual worlds.",
                    "Cryptocurrency is reshaping finance and challenging traditional systems."
                ],
                tags: [
                    "Innovation",
                    "Design",
                    "Tech Trends",
                    "UI/UX",
                    "Digital Design",
                    "Tech Revolution",
                    "User Experience",
                    "Coding",
                    "AI & Robotics",
                    "Sustainability",
                    "Cybersecurity",
                    "Design Thinking",
                    "Virtual Reality",
                    "Data Science",
                    "Startups",
                    "Graphic Design",
                    "Gaming",
                    "Digital Marketing",
                    "IoT",
                    "Artificial Intelligence",
                    "Accessibility",
                    "Space Tech",
                    "Mobile Apps",
                    "Eco-Design",
                    "Blockchain",
                    "Smart Cities",
                    "Web Development",
                    "Augmented Reality",
                    "Data Privacy",
                    "Healthcare Tech",
                    "Product Design",
                    "Cryptocurrency",
                    "3D Printing",
                    "UX/UI Design",
                    "AI in Healthcare",
                    "Digital Illustration",
                    "Cybersecurity",
                    "Sustainable Cities",
                    "Tech Entrepreneurship",
                    "Wearable Tech",
                    "AR/VR Gaming",
                    "Cryptocurrency"
                ]
            },
            4: {
                titles: [
                    "Fashion Forward: The Latest Trends",
                    "Red Carpet Glamour: Celebrity Styles",
                    "Luxury Lifestyle: Where Elegance Meets Exclusivity",
                    "Haute Couture: Unveiling the Art of Design",
                    "Chic and Timeless: Fashion for Every Occasion",
                    "Beauty Unveiled: Makeup and Skincare Secrets",
                    "Runway Elegance: Designer Collections Spotlight",
                    "Wardrobe Essentials: Building Your Fashion Arsenal",
                    "Street Style Chronicles: Urban Fashion Statements",
                    "Elegance Personified: Iconic Fashion Icons",
                    "Artistry in Fashion: Creative Designers at Work",
                    "The Power of Accessories: Elevating Your Look",
                    "Glamour Meets Sustainability: Eco-Friendly Fashion",
                    "The World of Fragrance: Scents That Define Luxury",
                    "Fashionistas' Guide to Traveling in Style",
                    "Redefining Beauty Standards: Diversity in Fashion",
                    "The Essence of Luxury: Fashion Editorials",
                    "Timeless Classics: Wardrobe Staples That Never Fade",
                    "From Catwalk to Sidewalk: Fashion Transcends Boundaries",
                    "Elevate Your Home: Interior Design and Decor",
                    "Fashion as Art: Exploring the Creative Process",
                    "The Iconic Little Black Dress: A Timeless Must-Have",
                    "Beauty Rituals: Unveiling the Secrets of Skincare",
                    "Emerging Fashion Talent: Rising Stars in Design",
                    "Effortless Elegance: Dressing for Casual Chic",
                    "High Fashion Fusion: Blending Cultures and Styles",
                    "Fashion's Impact: From Runway to Real Life",
                    "Celebrity Beauty Secrets: A Glimpse Behind the Scenes",
                    "Luxury Lifestyle Destinations: Where Fashion Meets Travel",
                    "The Art of Dressing: Expressing Your Unique Style",
                    "Bold and Beautiful: Fashion That Makes a Statement",
                    "The Timeless Trench Coat: A Fashion Icon Reimagined",
                    "Glowing Skin: Mastering the Art of Makeup",
                    "Fashion and Technology: Innovations That Redefine Style",
                    "The Allure of Vintage: Timeless Pieces With a Story",
                    "Sustainable Luxury: Fashion That Cares for the Planet",
                    "Fashion for All: Inclusivity and Diversity on the Runway",
                    "The Power of Color: How Hues Define Fashion Trends",
                    "Effortless Elegance: Dressing With Confidence",
                    "Couture Creations: Behind the Scenes of High Fashion",
                    "The Magic of Accessories: Elevating Your Look",
                    "Wardrobe Essentials: Building Your Style Foundation",
                    "The Intersection of Art and Fashion: A Creative Journey",
                    "Celebrity Style Icons: A Look at Timeless Fashion",
                    "The Beauty of Minimalism: Less Is More in Fashion",
                    "Eco-Friendly Fashion: Where Sustainability Meets Style"
                ],
                excerpts: [
                    "Stay in the know with the latest fashion trends that set the pace for the season.",
                    "Get a glimpse of celebrity red carpet styles and the glamour that lights up events.",
                    "Experience the epitome of luxury living where elegance meets exclusivity.",
                    "Explore the artistry of haute couture and the craftsmanship behind every design.",
                    "Discover chic and timeless fashion pieces perfect for every occasion.",
                    "Unlock the secrets of beauty with makeup and skincare tips from the experts.",
                    "Dive into the world of high fashion with spotlights on designer collections.",
                    "Build your fashion arsenal with wardrobe essentials that never go out of style.",
                    "Explore urban fashion statements in the vibrant world of street style.",
                    "Celebrate iconic fashion icons who personify elegance and style.",
                    "Witness the creative process of designers as they shape the world of fashion.",
                    "Elevate your look with the power of accessories that make a statement.",
                    "Experience glamour while staying eco-friendly with sustainable fashion choices.",
                    "Indulge in the world of fragrances that define luxury and sophistication.",
                    "Travel in style with our guide to fashionistas' must-have travel essentials.",
                    "Celebrate diversity and inclusivity in fashion, redefining beauty standards.",
                    "Immerse yourself in fashion editorials that capture the essence of luxury.",
                    "Discover timeless wardrobe staples that remain fashionable through the years.",
                    "See how fashion transcends boundaries, from the catwalk to everyday life.",
                    "Transform your living space with interior design and decor that exude elegance.",
                    "Witness fashion as an art form, exploring the creative process of designers.",
                    "Experience the allure of the iconic little black dress, a timeless classic.",
                    "Unveil beauty rituals and skincare secrets for radiant and flawless skin.",
                    "Spotlight on emerging talent as rising stars make their mark in the fashion world.",
                    "Master the art of dressing casually chic with effortless elegance.",
                    "Explore the fusion of cultures and styles that redefine high fashion.",
                    "Discover how fashion impacts real life, from the runway to everyday wear.",
                    "Go behind the scenes to uncover celebrity beauty secrets and routines.",
                    "Explore luxury lifestyle destinations where fashion meets the world of travel.",
                    "Express your unique style through the art of dressing and fashion choices.",
                    "Make a statement with bold and beautiful fashion that turns heads.",
                    "Reimagine the timeless trench coat, an iconic fashion piece with a fresh twist.",
                    "Achieve a radiant and glowing look with makeup techniques and tips.",
                    "Witness the intersection of technology and fashion with innovative trends.",
                    "Embrace the charm of vintage fashion, where each piece carries a unique story.",
                    "Choose fashion that cares for the planet with sustainable and eco-friendly luxury.",
                    "Celebrate inclusivity and diversity on the runway, where fashion is for all.",
                    "Discover the power of color in fashion trends and how hues define style.",
                    "Dress with confidence and embrace effortless elegance in every outfit.",
                    "Step into the world of couture creations and the craftsmanship behind high fashion.",
                    "Elevate your look with the magic of accessories that complete your style.",
                    "Build your style foundation with essential wardrobe pieces that stand the test of time.",
                    "Embark on a creative journey where art and fashion intersect in captivating ways.",
                    "Explore the fashion choices of celebrity style icons and their timeless influence.",
                    "Discover the beauty of minimalism in fashion, where less is more.",
                    "Choose sustainability and style with eco-friendly fashion that makes a difference."
                ],
                tags: [
                    "Fashion Trends",
                    "Red Carpet Glamour",
                    "Luxury Lifestyle",
                    "Haute Couture",
                    "Chic and Timeless Fashion",
                    "Beauty Secrets",
                    "Designer Collections",
                    "Wardrobe Essentials",
                    "Street Style",
                    "Fashion Icons",
                    "Creative Designers",
                    "Fashion Accessories",
                    "Eco-Friendly Fashion",
                    "Fragrances",
                    "Travel in Style",
                    "Diversity in Fashion",
                    "Fashion Editorials",
                    "Timeless Classics",
                    "Fashion Transcends Boundaries",
                    "Interior Design and Decor",
                    "Fashion as Art",
                    "Little Black Dress",
                    "Skincare Secrets",
                    "Emerging Fashion Talent"
                ]
            },
            5: {
                titles: [
                    "Elevate Your Brand: Creative Advertising Solutions",
                    "Web Development Excellence: Crafting Digital Experiences",
                    "Turning Ideas into Reality: Implementation with Precision",
                    "Strategic Advertising: Captivate Your Audience",
                    "Designing the Future: Innovative Web Solutions",
                    "Precision in Execution: Bringing Plans to Life",
                    "Unleash Creativity: Advertising That Resonates",
                    "Digital Transformation: Building Your Online Presence",
                    "From Concept to Completion: Seamless Implementation",
                    "Crafting Visual Stories: Compelling Advertising Campaigns",
                    "Web Development Mastery: User-Centric Designs",
                    "Turning Visions into Success: Effective Implementation",
                    "Creating Impact: Advertising That Gets Noticed",
                    "Digital Magic: Transforming Your Web Presence",
                    "Efficiency in Action: Implementation That Works",
                    "Inspire Action: Persuasive Advertising Strategies",
                    "Web Development Innovations: Engaging User Interfaces",
                    "Executing Excellence: Implementation at Its Best",
                    "Captivating Audiences: Memorable Advertising Campaigns",
                    "Web Development Beyond Boundaries: Responsive Design",
                    "Implementation with Precision: Turning Plans into Reality",
                    "Designing Tomorrow: Futuristic Advertising Concepts",
                    "Online Excellence: Crafting Dynamic Web Solutions",
                    "Implementation Excellence: Turning Concepts into Results",
                    "Advertising that Shines: Sparking Imagination",
                    "Crafting Digital Experiences: Web Development Unleashed",
                    "Implementation Mastery: Precision and Quality",
                    "Impactful Advertising: Making Brands Shine",
                    "Digital Innovations: Web Development at its Finest",
                    "Effortless Implementation: Bringing Dreams to Life",
                    "Advertising Strategy: Where Creativity Meets Strategy",
                    "Web Development Magic: Seamless User Journeys",
                    "Implementation Excellence: Turning Goals into Achievements",
                    "Advertising That Speaks Volumes: Persuasive Messaging",
                    "Digital Frontier: Exploring New Web Horizons",
                    "Precision Implementation: Bringing Ideas to fruition",
                    "Advertising for Impact: Capturing Hearts and Minds",
                    "Innovative Web Solutions: Redefining User Experiences",
                    "Implementation That Matters: Achieving Milestones",
                    "Advertising with Purpose: Inspiring Action",
                    "Web Development Evolution: Embracing New Possibilities",
                    "Turning Vision into Reality: Implementation Expertise"
                ],
                excerpts: [
                    "Discover creative advertising solutions that elevate your brand and leave a lasting impression.",
                    "Experience web development excellence with digital experiences that set new standards.",
                    "Turn your ideas into reality with precise implementation that brings your vision to life.",
                    "Craft strategic advertising campaigns that captivate and engage your target audience.",
                    "Design the future of your online presence with innovative web solutions that inspire.",
                    "Witness precision in execution as we bring your plans to life with efficiency and expertise.",
                    "Unleash creativity in advertising that resonates with your audience and drives results.",
                    "Embark on a digital transformation journey, building a strong online presence.",
                    "From concept to completion, experience seamless implementation that delivers results.",
                    "Craft visual stories that compel and resonate with your audience through impactful advertising.",
                    "Mastery in web development with user-centric designs that enhance user experiences.",
                    "Turn visions into success stories with effective implementation that achieves goals.",
                    "Create impact with advertising that gets noticed and sparks imagination.",
                    "Experience digital magic as we transform your web presence into something extraordinary.",
                    "Witness efficiency in action with implementation that works like clockwork.",
                    "Inspire action with persuasive advertising strategies that drive engagement and conversions.",
                    "Explore web development innovations with engaging user interfaces that captivate users.",
                    "Experience execution excellence with implementation that brings concepts to life.",
                    "Captivate your audience with memorable advertising campaigns that leave an impression.",
                    "Web development beyond boundaries with responsive design that adapts to user needs.",
                    "Implement with precision, turning plans into reality and achieving desired results.",
                    "Design tomorrow with futuristic advertising concepts that push creative boundaries.",
                    "Craft online excellence with dynamic web solutions that engage and inspire.",
                    "Achieve implementation excellence, turning concepts into tangible results.",
                    "Shine through impactful advertising that sparks imagination and resonates with your audience.",
                    "Experience digital innovations with web development at its finest, embracing new possibilities.",
                    "Effortlessly implement your dreams, bringing them to life with precision and quality.",
                    "Advertising strategy where creativity meets strategy, delivering impactful messaging.",
                    "Discover web development magic with seamless user journeys that delight users.",
                    "Achieve implementation excellence, turning goals into achievements and milestones.",
                    "Advertising that speaks volumes, inspiring action and driving meaningful results.",
                    "Explore the digital frontier with web development that embraces new horizons.",
                    "Precision implementation that brings ideas to fruition with dedication and expertise.",
                    "Create advertising for impact, capturing hearts and minds with compelling messaging.",
                    "Innovative web solutions that redefine user experiences, setting new standards.",
                    "Implementation that matters, achieving milestones and delivering on promises.",
                    "Advertising with purpose, inspiring action and making brands shine.",
                    "Evolve your web development, embracing new possibilities and redefining online experiences.",
                    "Turn vision into reality with implementation expertise that delivers tangible results."
                ],
                tags: [
                    "Creative Advertising",
                    "Web Development Excellence",
                    "Implementation Precision",
                    "Strategic Advertising",
                    "Innovative Web Solutions",
                    "Execution Efficiency",
                    "Impactful Advertising",
                    "Digital Transformation",
                    "Seamless Implementation",
                    "Compelling Advertising Campaigns",
                    "User-Centric Web Development",
                    "Vision to Success",
                    "Advertising Impact",
                    "Digital Magic",
                    "Efficiency in Action",
                    "Persuasive Messaging",
                    "Engaging User Interfaces",
                    "Execution Excellence",
                    "Memorable Campaigns",
                    "Responsive Web Development",
                    "Concept to Reality",
                    "Futuristic Advertising",
                    "Online Excellence",
                    "Achievement Milestones",
                    "Purposeful Advertising",
                    "Digital Innovations",
                    "Dream Implementation",
                    "Creative Strategy",
                    "User-Centric Design",
                    "Achieving Goals",
                    "Impactful Messaging",
                    "Embracing Possibilities",
                    "Precision Implementation",
                    "Inspiring Action",
                    "Redefining User Experiences",
                    "Delivering Promises",
                    "Shining Brands",
                    "Web Development Evolution",
                    "Vision to Reality"
                ]
            }
        };

        this.initializeData();
    }

    initializeData() {
        const categoryData = this.dataByCategory[this.category];
        if (categoryData) {
            this.randomTitles = categoryData.titles;
            this.randomExcerpts = categoryData.excerpts;
            this.randomTags = categoryData.tags;
        } else {
            console.warn("Invalid category selected");
        }
    }
}
